#Problem 2
#Even Fibonacci numbers
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def even_fibonacci(limit):
    sum = 2 #account for initial even value of 2
    num1 = 1
    num2 = 2
    num3 = 0
    
    while num3 < limit:
        #find next number
        num3 = num1 + num2
        #check for even and if so, add to sum
        if num3 % 2 == 0:
            sum += num3
        #reset num1 and num2 to calculate new number in sequence
        num1 = num2
        num2 = num3
        
    return sum

print(even_fibonacci(4000000))